// Mock AI response generator for frontend-only demo

export const generateMockAIResponse = async (
    userMessage: string,
    chatHistory: Array<{ role: string; content: string }> = []
): Promise<string> => {
    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 1000 + Math.random() * 1000));

    // Simple mock responses based on keywords
    const lowerMessage = userMessage.toLowerCase();

    if (lowerMessage.includes("hello") || lowerMessage.includes("hi")) {
        return "Hello! How can I help you today?";
    }

    if (lowerMessage.includes("react")) {
        return `React is a popular JavaScript library for building user interfaces. Here are some key features:

- **Component-based architecture**: Build reusable UI components
- **Virtual DOM**: Efficient rendering and updates
- **Unidirectional data flow**: Makes debugging easier
- **Hooks**: Modern way to manage state and side effects

Would you like to know more about any specific aspect of React?`;
    }

    if (lowerMessage.includes("javascript") || lowerMessage.includes("js")) {
        return `JavaScript is a versatile programming language. Here's what makes it powerful:

1. **Dynamic typing** - Variables can hold any type of value
2. **First-class functions** - Functions are treated as values
3. **Prototype-based inheritance** - Objects can inherit from other objects
4. **Async/await** - Modern asynchronous programming

What would you like to explore next?`;
    }

    if (lowerMessage.includes("code") || lowerMessage.includes("example")) {
        return `Here's a simple code example:

\`\`\`typescript
function greet(name: string): string {
    return \`Hello, \${name}!\`;
}

const message = greet("World");
console.log(message); // Output: Hello, World!
\`\`\`

This is a basic TypeScript function that demonstrates type annotations and template literals.`;
    }

    if (lowerMessage.includes("table") || lowerMessage.includes("compare")) {
        return `Here's a comparison table:

| Feature | Option A | Option B |
|---------|----------|----------|
| Speed   | Fast     | Faster   |
| Cost    | Low      | Medium   |
| Quality | Good     | Excellent|

This demonstrates markdown table formatting.`;
    }

    // Default response
    return `I understand you said: "${userMessage}". 

This is a mock response in the frontend-only demo. In a full application, this would be generated by an AI service like Google Gemini.

You can ask me about:
- Programming languages (React, JavaScript, TypeScript)
- Code examples
- Comparison tables
- General questions

What would you like to know?`;
};

// Generate a short title from a message
export const generateMockTitle = (message: string): string => {
    const words = message.split(" ").slice(0, 6);
    const title = words.join(" ");
    return title.length > 50 ? title.slice(0, 47) + "..." : title;
};

